---
name: code verification
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - "master"
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: sccache
  IN_CI: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Build
        run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: rustfmt nightly
        run: |
          rustup toolchain install nightly-x86_64-unknown-linux-gnu
          rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: Install grcov
        run: cargo install grcov
      - name: Add llvm-tools
        run: rustup component add llvm-tools-preview
      - name: Test
        run: make test
      - name: Compute coverage
        run: make cover
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
