---
name: code verification
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: sccache
  IN_CI: "true"

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Run sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad  # v0.0.9
      - name: Build
        run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Run sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad  # v0.0.9
      - name: rustfmt nightly
        run: |
          rustup toolchain install nightly-x86_64-unknown-linux-gnu
          rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.13"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Run sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad  # v0.0.9
      - name: Install cargo-nextest
        uses: taiki-e/install-action@0fde6d128a3d980ceac30be8c8b8739abd963b81  # v2.70.0
        with:
          tool: cargo-nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@0fde6d128a3d980ceac30be8c8b8739abd963b81  # v2.70.0
        with:
          tool: cargo-llvm-cov
      - name: Test
        run: make test cover
      - name: Upload coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2  # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
